# Generated by Django 4.2.1 on 2024-04-22 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0002_account_clientcontact_clientgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_phone', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.employee')),
            ],
            options={
                'unique_together': {('id', 'date', 'department_id', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientcontact',
            name='account_number',
        ),
        migrations.AlterUniqueTogether(
            name='clientgroup',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ClientContact',
        ),
        migrations.DeleteModel(
            name='ClientGroup',
        ),
    ]
