# Generated by Django 4.2.1 on 2024-04-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0003_department_employee_timesheet_users_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
    ]
