# Generated by Django 4.2.1 on 2024-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0005_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
