# Generated by Django 4.2.1 on 2024-04-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0006_alter_employee_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_role', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('abn', models.IntegerField(max_length=11, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('client_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('client_id', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.clientgroup'),
        ),
    ]
