# Generated by Django 4.2.1 on 2024-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0007_account_clientgroup_clientcontact_account_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='industry',
            field=models.CharField(max_length=255),
        ),
    ]
