# Generated by Django 4.2.1 on 2024-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0008_alter_clientgroup_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='abn',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
