# Generated by Django 4.2.1 on 2024-04-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0009_alter_account_abn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='abn',
            field=models.IntegerField(max_length=15, unique=True),
        ),
    ]
