# Generated by Django 4.2.1 on 2024-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0011_alter_account_abn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('date', 'department_id', 'employee_id')},
        ),
    ]
