# Generated by Django 4.2.1 on 2024-04-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0012_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('deal_name', models.CharField(max_length=255)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.DurationField()),
                ('SLAs', models.TextField()),
                ('deal_status', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.deals')),
            ],
        ),
    ]
