# Generated by Django 4.2.1 on 2024-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0013_deals_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
