# Generated by Django 4.2.1 on 2024-06-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0014_alter_deals_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('phone_support_queries', models.CharField(max_length=15, unique=True)),
                ('email_support_queries', models.EmailField(max_length=254, unique=True)),
                ('material_supply_category', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoresBranchNames',
            fields=[
                ('ABN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('region_of_operation', models.CharField(max_length=200)),
                ('branch_contact', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.materialsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=10)),
                ('individual_price', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('approver', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('ABN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcapp.storesbranchnames')),
            ],
        ),
    ]
