# Generated by Django 4.2.1 on 2024-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0015_materialsupplier_storesbranchnames_materialinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinvoice',
            name='individual_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialinvoice',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='materialinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
