# Generated by Django 4.2.1 on 2024-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcapp', '0016_alter_materialinvoice_individual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinvoice',
            name='individual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
